### ISSUE TITLE
No colors

### ISSUE THREAD

**Issue by jmondo** [astrauka/TestRSpec#40]
When I run my tests I get output that looks like this: 
```
[32m.[0m[31mF[0m

Failures:

  1) WorkingTitle::Api::V1::ProjectProjectAnnouncedTypesController GET #index should filter by project_ids
     [31mFailure/Error: [0mresponse_count = response_hash[[31m[1;31m'[0m[31mdata[1;31m'[0m[31m[0m].count[0m
     [31m[0m
     [31mTypeError:[0m
     [31m  no implicit conversion of String into Integer[0m
     [36m# ./spec/controllers/working_title/api/v1/project_project_announced_types_controller_spec.rb:19:in `[]'[0m
     [36m# ./spec/controllers/working_title/api/v1/project_project_announced_types_controller_spec.rb:19:in `block (3 levels) in <main>'[0m
     [36m# ./spec/spec_helper.rb:120:in `block (3 levels) in <main>'[0m
     [36m# ./spec/spec_helper.rb:119:in `block (2 levels) in <main>'[0m
     [36m# -e:1:in `<main>'[0m
```

Any idea how I get the colors to highlight instead of printing the ANSI?

**Comment by jmondo** [comment]
![image](https://user-images.githubusercontent.com/603431/52661757-8febd100-2eb7-11e9-811c-65cea0876d4c.png)

actually this is more useful, since github tried to do some work on my paste. ^

**Comment by OlegSmelov** [comment]
As far as I know, Sublime output panel is not a real terminal and does not support these escape sequences. To achieve colored output, this plugin assumes ASCII output and applies [its own syntax highlighting](https://github.com/astrauka/TestRSpec/blob/master/themes/TestConsole.tmLanguage).

In other words, the solution to your problem is to make RSpec not output any ANSI escape codes. I don't know why RSpec tries to use ANSI escape codes, can you share your config?

**Comment by jmondo** [comment]
well that was easy! just removed --color from .rspec
thanks!

**Comment by OlegSmelov** [comment]
I also have `--color` in my `~/.rspec`, but it doesn't use colors when output is not a terminal.
