### ISSUE TITLE
Compatibility with zeus

### ISSUE THREAD

**Issue by lbraun** [astrauka/TestRSpec#5]
Hi, thank you for developing this package. I'd like to run my tests with zeus (https://github.com/burke/zeus). Is there a way to customize the test running command to be "zeus rspec" instead of just "rspec"?

Something like this would be great!
https://github.com/maltize/sublime-text-2-ruby-tests#zeus-support

**Comment by lbraun** [comment]
Maybe this will work? https://github.com/astrauka/TestRSpec/pull/8

**Comment by astrauka** [comment]
Merged, does it work?

**Comment by lbraun** [comment]
Yeah, thanks! It's been working for me for a while now.

**Comment by astrauka** [comment]
:+1:

**Comment by astrauka** [comment]
Btw why are you using zeus instead of spring? @lbraun

**Comment by lbraun** [comment]
Because I like all the pretty colors when it loads 😉 

Actually, everyone on my last project was using it, and I got comfortable with it. I've had some reliability issues with spring on my current project too.

**Comment by barhot** [comment]
Zeus works almost 10 times faster than Spring for my App on OSX.

By the way, setting up TestRSpec from Package Control doesn't include [rspec_command](https://github.com/astrauka/TestRSpec/blob/master/Preferences.sublime-settings#L9) which allows to use `zeus test` instead of `rspec` command, so I had to reinstall the package from the repo.

**Comment by astrauka** [comment]
@barhot will make a new release to push the changes to package manager
